version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build:
      context: .
      dockerfile: auth-service.Dockerfile
    environment:
      MYSQL_DSN: "user:password@tcp(mysql:3306)/dbname"
      JWT_SECRET: "your_secret_key"
      AUTH_SERVICE_ADDRESS: ":8000"
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  profile-service:
    build:
      context: .
      dockerfile: profile-service.Dockerfile
    environment:
      MYSQL_DSN: "user:password@tcp(mysql:3306)/dbname"
      PROFILE_SERVICE_ADDRESS: ":8001"
    depends_on:
      - mysql
    ports:
      - "8001:8001"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway.Dockerfile
    environment:
      AUTH_SERVICE_ADDRESS: "http://auth-service:8000"
      PROFILE_SERVICE_ADDRESS: "http://profile-service:8001"
    depends_on:
      - auth-service
      - profile-service
    ports:
      - "8080:8080"

volumes:
  mysql_data: