version: '3.8'

networks:
  nainfo:

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nainfo

  auth-service:
    build:
      context: .
      dockerfile: auth-service.Dockerfile
    environment:
      MYSQL_DSN: "${MYSQL_DSN}"
      JWT_SECRET: "${JWT_SECRET}"
      AUTH_SERVICE_ADDRESS: ":8000"
      PROFILE_SERVICE_GRPC_ADDRESS: "${PROFILE_SERVICE_GRPC_ADDRESS}"
    volumes:
      - ./auth-service:/app
      - ./shared:/shared
    working_dir: /app
    command: air
    ports:
      - "8000:8000"
    networks:
      - nainfo

  profile-service:
    build:
      context: .
      dockerfile: profile-service.Dockerfile
    environment:
      MYSQL_DSN: "${MYSQL_DSN}"
      PROFILE_SERVICE_ADDRESS: ":8001"
      PROFILE_SERVICE_GRPC_ADDRESS: ":50051"
    volumes:
      - ./profile-service:/app
      - ./shared:/shared
    working_dir: /app
    command: air
    ports:
      - "8001:8001"
    networks:
      - nainfo

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway.Dockerfile
    environment:
      AUTH_SERVICE_ADDRESS: "${AUTH_SERVICE_ADDRESS}"
      PROFILE_SERVICE_ADDRESS: "${PROFILE_SERVICE_ADDRESS}"
    volumes:
      - ./api-gateway:/app
      - ./shared:/shared
    working_dir: /app
    command: air
    ports:
      - "8080:8080"
    networks:
      - nainfo
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8082:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_HOST: mysql
    networks:
      - nainfo

volumes:
  mysql_data: